const { chromium } = require('playwright');
const { readFileSync, mkdirSync, writeFileSync, existsSync, statSync } = require('node:fs');
const { join, extname } = require('node:path');
const http = require('node:http');
const assert = require('node:assert/strict');
const root=join(__dirname,'..','dist'), output=join(__dirname,'..','output','radar-freshness');mkdirSync(output,{recursive:true});
const types={'.html':'text/html','.css':'text/css','.svg':'image/svg+xml','.jpg':'image/jpeg','.png':'image/png','.json':'application/json','.csv':'text/csv'};
const server=http.createServer((req,res)=>{const pathname=new URL(req.url,'http://x').pathname;let file=join(root,pathname);if(pathname.endsWith('/'))file=join(file,'index.html');if(!existsSync(file)||statSync(file).isDirectory()){res.writeHead(404);res.end();return}res.setHeader('content-type',types[extname(file)]||'application/octet-stream');res.end(readFileSync(file));});
const checks=[];const check=(name,value)=>{checks.push(name);assert.ok(value,name)};
(async()=>{
 const {radarRecords:records,radarRoutes:routes}=await import('../scripts/radar.mjs');const{freshnessState,radarNotice}=await import('../scripts/radar-freshness.mjs');const{validateRadarHtml,validateRadarJson,validateRadarCsv}=await import('../scripts/radar-validation.mjs');
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;const browser=await chromium.launch({headless:true});
 try {
  for(const width of [1440,768,390,320])for(const javaScriptEnabled of [true,false])for(const date of ['2026-07-17T18:08:42Z','2026-07-17T18:08:43Z','2026-07-18T18:08:43Z','2026-09-16T14:00:00Z']) {
   const context=await browser.newContext({viewport:{width,height:900},javaScriptEnabled});const page=await context.newPage();await page.clock.setFixedTime(new Date(date));
   for(const [i,route]of routes.entries()){
    const tag=`${route.path} ${width} js=${javaScriptEnabled} ${date}`,requests=[],errors=[];const onRequest=r=>requests.push(r.url()),onError=e=>errors.push(String(e));page.on('request',onRequest);page.on('pageerror',onError);
    const response=await page.goto(origin+route.path,{waitUntil:'load'});await page.evaluate(()=>document.fonts.ready);const body=await page.locator('body').innerText();
    check(tag+' status',response.status()===200);check(tag+' static validator',validateRadarHtml(await response.text(),route));check(tag+' permanent notice',body.includes(radarNotice));check(tag+' archive visible',body.includes('JULY 2026 ARCHIVE'));check(tag+' no current claim',!body.includes('CURRENT OBSERVATION')&&!body.includes('Use the current 5.2.0'));check(tag+' no overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));check(tag+' one H1',await page.locator('h1').count()===1&&await page.locator('h1').isVisible());check(tag+' canonical',await page.locator('link[rel=canonical]').getAttribute('href')==='https://getdeclarix.com'+route.path);
    const graph=JSON.parse(await page.locator('script[type="application/ld+json"]').innerText())['@graph'];const schema=graph.find(x=>['CollectionPage','Article'].includes(x['@type']));check(tag+' dated schema',schema.dateModified==='2026-09-16'&&schema.datePublished==='2026-07-17'&&schema.description===route.description);
    const nodes=page.locator('[data-radar-freshness]');check(tag+' static archive state unchanged',(await nodes.evaluateAll(ns=>ns.every(n=>n.dataset.freshnessState==='archived_observation'))));
    if(javaScriptEnabled){const expected=i?[freshnessState(records[i-1],new Date(date)),freshnessState(records[i-1],new Date(date))]:records.map(r=>freshnessState(r,new Date(date)));check(tag+' shared clock assessment',JSON.stringify(await nodes.evaluateAll(ns=>ns.map(n=>n.dataset.clockState)))===JSON.stringify(expected));check(tag+' supplemental limit',body.toLowerCase().includes('not a source recheck.'))}
    else{check(tag+' JS control hidden',await page.locator('[data-js-control]:visible').count()===0);check(tag+' fallback assessment',body.toLowerCase().includes('clock assessment unavailable. check the official source.'))}
    if(i){check(tag+' official source link',await page.locator('a[href="'+records[i-1].source.url+'"]').count()===2);check(tag+' original hash',body.includes(records[i-1].source.sha256));check(tag+' original history',await page.locator('time[datetime="'+records[i-1].history[0].observedAt+'"]').count()>0)}
    if(!i){
     check(tag+' all records initially visible',await page.locator('[data-radar-result]:visible').count()===5);
     for(const ext of ['json','csv']){
      const href='/downloads/cds-operations-radar-v2.'+ext,link=page.locator('a[download][href="'+href+'"]');check(tag+' download visible '+ext,await link.isVisible());const wait=page.waitForEvent('download');await link.click();const download=await wait;check(tag+' download name '+ext,download.suggestedFilename()===href.split('/').pop());check(tag+' download success '+ext,await download.failure()===null);const text=readFileSync(await download.path(),'utf8');check(tag+' download context '+ext,ext==='json'?validateRadarJson(text):validateRadarCsv(text));check(tag+' downloaded bytes '+ext,text===readFileSync(join(root,href),'utf8'));
     }
     if(javaScriptEnabled){await page.locator('[name=q]').fill('workarounds');check(tag+' search filter',await page.locator('[data-radar-result]:visible').count()===1);check(tag+' URL query',new URL(page.url()).searchParams.get('q')==='workarounds');await page.locator('[data-radar-clear]').click();check(tag+' clear focus',await page.locator('[name=q]').evaluate(n=>document.activeElement===n));await page.locator('[name=topic]').selectOption('service-status');check(tag+' topic filter',await page.locator('[data-radar-result]:visible').count()===1);await page.locator('[data-radar-clear]').click();await page.locator('[name=stage]').selectOption('service_access');check(tag+' workflow filter',await page.locator('[data-radar-result]:visible').count()===1);await page.locator('[data-radar-clear]').click();await page.locator('[name=state]').selectOption('expired');check(tag+' state filter',await page.locator('[data-radar-result]:visible').count()===records.filter(r=>freshnessState(r,new Date(date))==='expired').length);await page.locator('[data-radar-clear]').click();await page.locator('[name=q]').fill('no-such-change');check(tag+' empty message',await page.locator('[data-radar-empty]').isVisible());await page.locator('[data-radar-clear]').click();await page.locator('[name=q]').focus();await page.keyboard.press('Tab');check(tag+' keyboard topic',await page.locator('[name=topic]').evaluate(n=>document.activeElement===n));}
     else check(tag+' no-JS explanation',body.includes('JavaScript is off. All five archive records are shown.'));
    }
    if(javaScriptEnabled&&date.startsWith('2026-09-16')){
     if(i){await page.evaluate(()=>{Object.defineProperty(navigator,'share',{value:undefined,configurable:true});Object.defineProperty(navigator,'clipboard',{value:{writeText:async value=>{window.copied=value}},configurable:true})});await page.locator('[data-radar-share]').click();check(tag+' clipboard share',await page.evaluate(()=>window.copied===location.href));await page.evaluate(()=>Object.defineProperty(navigator,'share',{value:async value=>{window.shared=value},configurable:true}));await page.locator('[data-radar-share]').click();check(tag+' native share',await page.evaluate(()=>window.shared.url===location.href));}
     await page.addScriptTag({path:require.resolve('axe-core/axe.min.js')});const axe=await page.evaluate(()=>axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}}));check(tag+' WCAG '+JSON.stringify(axe.violations.map(x=>({id:x.id,nodes:x.nodes.map(n=>n.target)}))),axe.violations.length===0);await page.screenshot({path:join(output,`${i}-${width}.png`),fullPage:true});
    }
    check(tag+' no third-party requests',requests.every(url=>url.startsWith(origin+'/')));check(tag+' no runtime errors',errors.length===0);page.off('request',onRequest);page.off('pageerror',onError);
   }
   await context.close();
  }
  const boundaryContext=await browser.newContext({viewport:{width:390,height:900}});const boundaryPage=await boundaryContext.newPage();
  await boundaryPage.clock.setFixedTime(new Date('2026-07-18T18:08:42Z'));await boundaryPage.goto(origin+routes[0].path+'?topic=service-status');check('deep-linked filter',await boundaryPage.locator('[data-radar-result]:visible').count()===1);
  const first=boundaryPage.locator('[data-radar-result]').first();check('browser before expiry',await first.getAttribute('data-clock-state')==='within_recorded_window');await boundaryPage.clock.setFixedTime(new Date('2026-07-18T18:08:43Z'));await boundaryPage.locator('[name=q]').fill('CDS');check('browser at expiry after interaction',await first.getAttribute('data-clock-state')==='expired');
  await first.evaluate(n=>{n.dataset.freshUntil='invalid'});await boundaryPage.locator('[name=q]').fill('');check('invalid browser dates fail closed',await first.getAttribute('data-clock-state')==='unknown');check('archive survives invalid clock input',await first.getAttribute('data-freshness-state')==='archived_observation');await boundaryContext.close();
  for(const file of ['llms.txt','llms-full.txt']){const text=readFileSync(join(root,file),'utf8');for(const route of routes){const line=text.split('\n').find(l=>l.includes('https://getdeclarix.com'+route.path+')'));check(file+' safe discovery '+route.path,line===`- [${route.title}](https://getdeclarix.com${route.path}): ${route.description}`&&line.includes('not live status'))}}
  for(const version of ['v1','v2'])for(const ext of ['json','csv']){const text=await(await fetch(origin+'/downloads/cds-operations-radar-'+version+'.'+ext)).text();check(version+' '+ext+' explicitly versioned portable context',ext==='json'?validateRadarJson(text):validateRadarCsv(text))}
  writeFileSync(join(output,'BROWSER_TESTS.json'),JSON.stringify({status:'PASS',checks:checks.length,contexts:192,scope:'Six routes; four widths; JS/no-JS; same static artifact before/at observation, at expiry and in September; actual downloads, filters, keyboard/share, metadata, automated WCAG and no third-party calls.'},null,2));console.log(JSON.stringify({status:'PASS',checks:checks.length}));
 }finally{await browser.close();await new Promise(r=>server.close(r))}
})().catch(e=>{console.error(e);process.exitCode=1});
