const {chromium}=require('playwright');const{readFileSync,mkdirSync,writeFileSync,existsSync,statSync}=require('node:fs');const{join,extname}=require('node:path');const http=require('node:http');const assert=require('node:assert/strict');
const root=join(__dirname,'..','dist'),output=join(__dirname,'..','output','registration-kit');mkdirSync(output,{recursive:true});
const types={'.html':'text/html','.css':'text/css','.svg':'image/svg+xml','.jpg':'image/jpeg','.png':'image/png','.xml':'application/xml','.txt':'text/plain','.md':'text/markdown','.csv':'text/csv'};
const server=http.createServer((req,res)=>{let pathname=decodeURIComponent(new URL(req.url,'http://x').pathname);let file=join(root,pathname);if(pathname.endsWith('/'))file=join(file,'index.html');if(!existsSync(file)||statSync(file).isDirectory()){res.writeHead(404);res.end();return}res.setHeader('content-type',types[extname(file)]||'application/octet-stream');res.end(readFileSync(file));});
const checks=[];const check=(name,value)=>{checks.push(name);assert.ok(value,name)};
(async()=>{const{registrationRoute:route}=await import('../scripts/registration-kit.mjs');const{registrationContract:contract,validateRegistrationMarkdown,validateRegistrationCsv,validateRegistrationHtml}=await import('../scripts/registration-validation.mjs');await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;const browser=await chromium.launch({headless:true});try{
 for(const width of [1440,768,390,320])for(const javaScriptEnabled of [true,false])for(const date of ['2026-09-20T12:00:00Z','2026-09-21T12:00:00Z','2026-09-22T12:00:00Z']){
  const context=await browser.newContext({viewport:{width,height:900},javaScriptEnabled});const page=await context.newPage();await page.clock.setFixedTime(new Date(date));const requests=[],errors=[];page.on('request',r=>requests.push(r.url()));page.on('pageerror',e=>errors.push(String(e)));const response=await page.goto(origin+route.path,{waitUntil:'networkidle'});const tag=`${width} js=${javaScriptEnabled} ${date}`;const body=await page.locator('body').innerText();
  check(tag+' status',response.status()===200);check(tag+' static HTML validated',validateRegistrationHtml(await response.text(),route));check(tag+' one visible H1',await page.locator('h1').count()===1&&await page.locator('h1').isVisible());check(tag+' no overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));check(tag+' canonical',await page.locator('link[rel=canonical]').getAttribute('href')==='https://getdeclarix.com'+route.path);check(tag+' edition visible',body.includes('16 September 2026'));check(tag+' recorded deadline visible',body.includes('published response deadline of 21 September 2026'));check(tag+' reuse context visible',body.includes(route.boundary));
  for(const phrase of contract.prohibited_current_claims)check(tag+' no '+phrase,!body.toLowerCase().includes(phrase.toLowerCase()));
  const graph=JSON.parse(await page.locator('script[type="application/ld+json"]').innerText())['@graph'];const article=graph.find(x=>x['@type']==='Article');check(tag+' schema checked date',article.dateModified==='2026-09-16');check(tag+' schema agrees',article.description===route.description&&article.headline===route.h1);check(tag+' official links',await page.locator('a[href="'+route.sources[0].url+'"]').count()>0);check(tag+' no submission inputs',await page.locator('form,input[type=file]').count()===0);
  for(const [i,asset]of route.resourceKit.assets.entries()){
   const link=page.locator('a[download][href="'+asset.href+'"]');check(tag+' download visible '+i,await link.isVisible());const downloadWait=page.waitForEvent('download');await link.click();const download=await downloadWait;check(tag+' correct file '+i,download.suggestedFilename()===asset.href.split('/').pop());check(tag+' download works '+i,await download.failure()===null);const downloaded=readFileSync(await download.path(),'utf8');check(tag+' file context '+i,i===0?validateRegistrationMarkdown(downloaded):validateRegistrationCsv(downloaded));check(tag+' served file exact '+i,downloaded===readFileSync(join(root,asset.href),'utf8'));
  }
  if(javaScriptEnabled){check(tag+' download events',await page.evaluate(()=>window.dataLayer.filter(x=>x.event==='registration_kit_downloaded').length===2));await page.addScriptTag({path:require.resolve('axe-core/axe.min.js')});const axe=await page.evaluate(()=>axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}}));check(tag+' WCAG '+JSON.stringify(axe.violations.map(v=>v.id)),axe.violations.length===0)}
  check(tag+' no third-party request',requests.every(url=>url.startsWith(origin+'/')));check(tag+' no runtime errors',errors.length===0);
  if(javaScriptEnabled&&date.startsWith('2026-09-22'))await page.screenshot({path:join(output,`registration-${width}.png`),fullPage:true});await context.close();
 }
 for(const file of ['llms.txt','llms-full.txt']){const text=readFileSync(join(root,file),'utf8');const line=text.split('\n').find(l=>l.includes('https://getdeclarix.com'+route.path));check(file+' safe neutral discovery',line===`- [Indexed route: ${route.path}](https://getdeclarix.com${route.path}): Indexed route; product or commercial copy awaits claim alignment and is omitted from this discovery summary.`)}
 const sitemap=readFileSync(join(root,'sitemap.xml'),'utf8');check('sitemap edition matches',sitemap.includes(`<loc>https://getdeclarix.com${route.path}</loc><lastmod>2026-09-16</lastmod>`));
 writeFileSync(join(output,'BROWSER_TESTS.json'),JSON.stringify({status:'PASS',checks:checks.length,scope:'24 contexts: 4 widths, JS on/off, before/on/after recorded deadline; same built artifact, downloaded bytes, schema/discovery/source dates, automated WCAG. Not legal or publication clearance.'},null,2));console.log(JSON.stringify({status:'PASS',checks:checks.length}));
 }finally{await browser.close();await new Promise(r=>server.close(r))}})().catch(e=>{console.error(e);process.exitCode=1});
