const {chromium}=require('playwright');const{readFileSync,mkdirSync,writeFileSync,existsSync,statSync}=require('node:fs');const{join,extname}=require('node:path');const http=require('node:http');const assert=require('node:assert/strict');
const root=join(__dirname,'..','dist'),output=join(__dirname,'..','output','research-lineage');mkdirSync(output,{recursive:true});const types={'.html':'text/html','.css':'text/css','.svg':'image/svg+xml','.csv':'text/csv','.jpg':'image/jpeg','.png':'image/png'};
const server=http.createServer((req,res)=>{let file=join(root,new URL(req.url,'http://x').pathname);if(existsSync(file)&&statSync(file).isDirectory())file=join(file,'index.html');if(!existsSync(file)){res.writeHead(404);res.end();return}res.setHeader('content-type',types[extname(file)]||'application/octet-stream');res.end(readFileSync(file))});let count=0;const check=(name,value)=>{count++;assert.ok(value,name)};
(async()=>{const{reports}=await import('../scripts/reports.mjs');const{authorityRoutes,authorityAssets}=await import('../scripts/authority-library.mjs');const{lineage}=await import('../scripts/research-lineage.mjs');const{validateResearchHtml}=await import('../scripts/research-validation.mjs');const routes=[reports[0],authorityRoutes.find(x=>x.kind==='burden-report')];await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;const browser=await chromium.launch({headless:true});
try{for(const width of [1440,768,390,320])for(const javaScriptEnabled of [true,false]){
 const context=await browser.newContext({viewport:{width,height:900},javaScriptEnabled});const page=await context.newPage();
 for(const [i,route]of routes.entries()){
  const tag=`${i} ${width} JS=${javaScriptEnabled}`,requests=[],errors=[];const onRequest=r=>requests.push(r.url()),onError=e=>errors.push(String(e));page.on('request',onRequest);page.on('pageerror',onError);
  const res=await page.goto(origin+route.path,{waitUntil:'load'});await page.evaluate(()=>document.fonts.ready);check(tag+' status',res.status()===200);check(tag+' source validator',validateResearchHtml(await res.text(),route));check(tag+' no overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));check(tag+' one H1',await page.locator('h1').count()===1&&await page.locator('h1').isVisible());
  check(tag+' notice visible',await page.locator('.research-notice').isVisible());const notice=await page.locator('.research-notice').innerText();check(tag+' method readable',notice.includes(i?lineage.hmrcMethod:lineage.originalMethod));check(tag+' reuse limits readable',notice.includes(i?lineage.hmrcNotice:lineage.originalNotice));check(tag+' no collection forms',await page.locator('form,input,textarea').count()===0);check(tag+' canonical',await page.locator('link[rel=canonical]').getAttribute('href')==='https://getdeclarix.com'+route.path);
  const assets=i?authorityAssets(route):route.downloads;
  for(const asset of assets){const link=page.locator(`a[download][href="${asset.href}"]`).first();check(tag+' link visible '+asset.href,await link.isVisible());const waiting=page.waitForEvent('download');await link.click();const download=await waiting;check(tag+' downloaded '+asset.href,await download.failure()===null);check(tag+' bytes '+asset.href,readFileSync(await download.path(),'utf8')===readFileSync(join(root,asset.href),'utf8'));check(tag+' filename',download.suggestedFilename()===asset.href.split('/').pop())}
  if(!i){await page.locator('[data-report-methodology]').click();check(tag+' methodology anchor',new URL(page.url()).hash==='#methodology');if(javaScriptEnabled){await page.evaluate(()=>{Object.defineProperty(navigator,'share',{value:undefined,configurable:true});Object.defineProperty(navigator,'clipboard',{value:{writeText:async v=>{window.copied=v}},configurable:true})});await page.locator('[data-report-share]').click();check(tag+' clipboard share',await page.evaluate(()=>Boolean(window.copied)));await page.evaluate(()=>Object.defineProperty(navigator,'share',{value:async v=>{window.shared=v},configurable:true}));await page.locator('[data-report-share]').click();check(tag+' native share',await page.evaluate(()=>Boolean(window.shared.url)))}}
  if(javaScriptEnabled){await page.addScriptTag({path:require.resolve('axe-core/axe.min.js')});const result=await page.evaluate(()=>axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}}));check(tag+' WCAG '+JSON.stringify(result.violations.map(x=>({id:x.id,nodes:x.nodes.map(n=>n.target)}))),result.violations.length===0);await page.screenshot({path:join(output,`${i}-${width}.png`),fullPage:true});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:join(output,`${i}-${width}-top.png`)});await page.locator('a[download]').first().focus();await page.keyboard.press('Tab');check(tag+' keyboard next control',await page.evaluate(()=>['A','BUTTON'].includes(document.activeElement.tagName)))}
  check(tag+' no third-party requests',requests.every(u=>u.startsWith(origin+'/')));check(tag+' no runtime errors',errors.length===0);page.off('request',onRequest);page.off('pageerror',onError);
 }
 await context.close();
}
const context=await browser.newContext({viewport:{width:1200,height:900}});const page=await context.newPage();
for(const [i,route]of routes.entries()){
 const assets=i?authorityAssets(route):route.downloads;const asset=assets.find(a=>a.href.endsWith('.svg'));await page.goto(origin+asset.href);check('SVG parsed '+i,await page.locator('parsererror').count()===0);check('SVG accessible name '+i,await page.locator('svg').getAttribute('aria-labelledby')==='title desc');
 const boxes=await page.locator('svg text').evaluateAll(ns=>ns.map(n=>{const b=n.getBBox();return{text:n.textContent,x:b.x,y:b.y,w:b.width,h:b.height}}));check('SVG bounds '+i+' '+JSON.stringify(boxes.filter(b=>b.x<35||b.x+b.w>1166||b.y<35||b.y+b.h>865)),boxes.every(b=>b.x>=35&&b.x+b.w<=1166&&b.y>=35&&b.y+b.h<=865));check('SVG no line overlaps '+i,boxes.every((b,j)=>!j||b.y>=boxes[j-1].y+boxes[j-1].h));await page.screenshot({path:join(output,`chart-${i}.png`)});
}
await context.close();writeFileSync(join(output,'BROWSER_TESTS.json'),JSON.stringify({status:'PASS',checks:count,scope:'Two pages, four widths, JS/no-JS; actual downloads, schema, source context, share, anchors, keyboard, WCAG, privacy and SVG text geometry.'},null,2)+'\n');console.log(JSON.stringify({status:'PASS',checks:count}));
}finally{await browser.close();await new Promise(r=>server.close(r))}})().catch(e=>{console.error(e);process.exitCode=1});
