const {chromium}=require('playwright');const {readFileSync,writeFileSync,mkdirSync,existsSync,statSync}=require('node:fs');const {join,extname}=require('node:path');const http=require('node:http');const assert=require('node:assert/strict');
const root=join(__dirname,'..','dist'),out=join(__dirname,'..','output','workpapers');mkdirSync(out,{recursive:true});let checks=0;const check=(name,v)=>{checks++;assert.ok(v,name)};
const types={'.html':'text/html','.css':'text/css','.svg':'image/svg+xml','.js':'text/javascript','.woff2':'font/woff2'};const server=http.createServer((req,res)=>{let p=join(root,new URL(req.url,'http://x').pathname);if(existsSync(p)&&statSync(p).isDirectory())p=join(p,'index.html');if(!existsSync(p)){res.writeHead(404);res.end();return}res.setHeader('content-type',types[extname(p)]||'application/octet-stream');res.end(readFileSync(p))});
(async()=>{const {authorityRoutes,authorityAssets}=await import('../scripts/authority-library.mjs');const {isWorkpaper,workpaperNotice}=await import('../scripts/workpaper-context.mjs');const {validateWorkpaperHtml}=await import('../scripts/workpaper-validation.mjs');const routes=authorityRoutes.filter(isWorkpaper);await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({headless:true});
try{for(const width of [1440,768,390,320])for(const javaScriptEnabled of [true,false]){
 const context=await browser.newContext({viewport:{width,height:900},javaScriptEnabled});const page=await context.newPage();
 for(const r of routes){const tag=r.slug+' '+width+' JS='+javaScriptEnabled,requests=[],errors=[];const request=x=>requests.push(x.url()),error=e=>errors.push(String(e));page.on('request',request);page.on('pageerror',error);
 const response=await page.goto(origin+r.path,{waitUntil:'load'});await page.evaluate(()=>document.fonts.ready);check(tag+' HTTP',response.status()===200);check(tag+' verifier',validateWorkpaperHtml(await response.text(),r));check(tag+' no overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));check(tag+' single visible H1',await page.locator('h1').count()===1&&await page.locator('h1').isVisible());check(tag+' visible provenance',await page.locator('.workpaper-notice').isVisible()&&(await page.locator('.workpaper-notice').innerText()).includes(workpaperNotice));check(tag+' canonical',await page.locator('link[rel=canonical]').getAttribute('href')==='https://getdeclarix.com'+r.path);
 const a=authorityAssets(r)[0],link=page.locator('a[download]');check(tag+' download visible',await link.count()===1&&await link.isVisible());check(tag+' download href',await link.getAttribute('href')===a.href);const promise=page.waitForEvent('download');await link.click();const file=await promise;check(tag+' real download',await file.failure()===null);check(tag+' download bytes',readFileSync(await file.path(),'utf8')===a.content);check(tag+' filename',file.suggestedFilename()===a.href.split('/').pop());
 for(const s of r.sources){const l=page.locator('.authority-sources').getByRole('link',{name:s.title,exact:true});check(tag+' source visible '+s.title,await l.isVisible());check(tag+' source href '+s.title,await l.getAttribute('href')===s.url)}
 check(tag+' no form collection',await page.locator('form,input,textarea').count()===0);
 if(javaScriptEnabled){await page.addScriptTag({path:require.resolve('axe-core/axe.min.js')});const result=await page.evaluate(()=>axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}}));check(tag+' WCAG '+JSON.stringify(result.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))),result.violations.length===0);await link.focus();await page.keyboard.press('Tab');check(tag+' keyboard',await page.evaluate(()=>['A','BUTTON'].includes(document.activeElement.tagName)));if(width===320||width===1440){await page.screenshot({path:join(out,r.slug+'-'+width+'.png'),fullPage:true})}}
 check(tag+' local-only requests',requests.every(x=>x.startsWith(origin+'/')));check(tag+' no runtime errors',errors.length===0);page.off('request',request);page.off('pageerror',error);
 }await context.close();
 }
 const context=await browser.newContext({viewport:{width:1200,height:1200}});const page=await context.newPage();
 for(const r of routes){const a=authorityAssets(r)[0];await page.goto(origin+a.href);check(r.slug+' SVG parsed',await page.locator('parsererror').count()===0);check(r.slug+' accessible name',await page.locator('svg').getAttribute('aria-labelledby')==='title desc');const boxes=await page.locator('svg text').evaluateAll(ns=>ns.map(n=>{const b=n.getBBox();return{text:n.textContent,x:b.x,y:b.y,w:b.width,h:b.height}}));const bad=boxes.filter(b=>b.x<39||b.x+b.w>1161||b.y<39||b.y+b.h>1161);check(r.slug+' bounds '+JSON.stringify(bad),bad.length===0);const overlaps=[];for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++){const a=boxes[i],b=boxes[j];if(Math.min(a.x+a.w,b.x+b.w)-Math.max(a.x,b.x)>1&&Math.min(a.y+a.h,b.y+b.h)-Math.max(a.y,b.y)>1)overlaps.push([a.text,b.text])}check(r.slug+' no text overlap '+JSON.stringify(overlaps),overlaps.length===0);for(const s of r.sources){const link=page.locator(`svg a[href="${s.url}"]`);check(r.slug+' portable link '+s.title,await link.count()===1&&await link.getAttribute('href')===s.url)}await page.screenshot({path:join(out,r.slug+'-sheet.png')});
 }await context.close();writeFileSync(join(out,'BROWSER_TESTS.json'),JSON.stringify({status:'PASS',checks,scope:'Eleven pages, four widths, JS/no-JS; actual downloads, visible dates/sources, WCAG, keyboard, privacy; all SVGs text bounds/overlap and clickable sources.'},null,2)+'\n');console.log(JSON.stringify({status:'PASS',checks}));
}finally{await browser.close();await new Promise(r=>server.close(r))}})().catch(e=>{console.error(e);process.exitCode=1});
